services:
  - type: web
    name: nss-management-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn nss_management.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_NAME
        value: "nss_db"
      - key: DB_USER
        value: "4Yq5eBnhFAZezXD.root"
      - key: DB_PASSWORD
        value: "N8hpZeVbhScZHeX1"
      - key: DB_HOST
        value: "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
      - key: DB_PORT
        value: "4000"
