# Generated by Django 6.0.4 on 2026-05-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regno', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
                ('address', models.TextField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_tab',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regno', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'blood_bank',
                'managed': True,
            },
        ),
    ]
