# Generated by Django 6.0.4 on 2026-05-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nssapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='regno',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
