# Generated by Django 6.0.4 on 2026-05-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nssapp', '0002_alter_bloodbank_phone_alter_bloodbank_regno'),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeCertificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('pledge_text', models.TextField()),
                ('pledge_date', models.DateField()),
                ('certificate_code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pledge_certificate',
                'managed': True,
            },
        ),
    ]
