# Generated by Django 6.0.4 on 2026-05-05 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nssapp', '0003_pledgecertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_day', models.CharField(max_length=50)),
                ('event_time', models.TimeField()),
                ('place', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to='nssapp.usertab')),
            ],
            options={
                'db_table': 'event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sender_role', models.CharField(max_length=50)),
                ('target_role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sender_id', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, to='nssapp.usertab')),
            ],
            options={
                'db_table': 'notification',
                'managed': True,
            },
        ),
    ]
